# Generated by Django 4.2.14 on 2024-08-23 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_stripe_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='stripe_product_price',
            new_name='stripe_product_price_id',
        ),
    ]
